server:
  #address: localhost
  address: 0.0.0.0
  port: 9091
spring:
  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer